### ISSUE TITLE
multidex后无法生成class2的差分包

### ISSUE THREAD

**Issue by xu-duqing** [alibaba/AndFix#105]
如题，项目超过64k限制的时候第二个dex文件无法生成.apatch文件？

**Comment by Comori** [comment]
我的项目中也碰到了这个问题。后来通过javaassit 修改了apkpatch-1.0.3.jar的源代码，即可以兼容分包的情况。

**Comment by xu-duqing** [comment]
@Comori  你比较机智啊！ apkpatch怎么没有开源。 能不能把你改过的jar包给我发一份？xu.duqing@gmail.com

**Comment by Comori** [comment]
![image](https://cloud.githubusercontent.com/assets/7588760/11831199/472103c2-a3e7-11e5-96a3-9c5bc1cbad82.png)

**Comment by Comori** [comment]
反编译看apkpatch的源代码，就会发现代码中只是针对classes.dex做了处理：
![image](https://cloud.githubusercontent.com/assets/7588760/11831464/6abc312e-a3e9-11e5-88f2-1bf43d1bb075.png)

我自己增加了一个方法：
   
![image](https://cloud.githubusercontent.com/assets/7588760/11831492/ac4faf58-a3e9-11e5-9f8a-2cc21f835949.png)

并且修改了DexDiffer的方法：

 
![image](https://cloud.githubusercontent.com/assets/7588760/11831604/a1a7e72c-a3ea-11e5-8db9-28a02beea664.png)

jar文件已发到你的邮箱，可以根据自己的需求再行修改！

**Comment by xu-duqing** [comment]
@Comori 谢谢

**Comment by taoweiji2008** [comment]
@Comori @xu-duqing 能发一份给我吗？

**Comment by taoweiji2008** [comment]
我的邮箱是 taoweiji2008@qq.com

**Comment by taoweiji2008** [comment]
@Comori @xu-duqing 能发一份给我吗？我的邮箱是 taoweiji2008@qq.com

**Comment by ZoroLu** [comment]
@Comori 同求一份修改后的 jar, 虽然大神已经给出主要代码，但是还是希望能得到一份，等有空我也自己参考你的代码折腾一下，如你有时间希望能发一份  guanquan.lu@gmail.com ，谢谢。

**Comment by Comori** [comment]
http://pan.baidu.com/s/1mgNMf4s(我自己写的一个java swing程序，双击运行即可)

**Comment by cokepanm** [comment]
希望官方能出个正式版，这个如果不支持确实很坑啊，我就说有些类能打补丁有些没有呢。。。

**Comment by BreezeDust** [comment]
@Comori 刚好遇见这个问题，谢啦，我在github上也搜索到了一个人写的
https://github.com/zhengyuqin/andfix_apkpatch_support_multidex

**Comment by heweimxcz** [comment]
跪求啊，这个jar能不能发给我一份

**Comment by heweimxcz** [comment]
我的邮箱heweimxcz@163.com

**Comment by heweimxcz** [comment]
@Comori 谢谢啦

**Comment by JoeyChen52** [comment]
反编译后我只找到了Dexdiffer类，没找到DexFileFactory。。。能不能把jar发我，我想要jar包不知道还有没有，谢谢。lyzhun@163.com
