### ISSUE TITLE
请问这个报错是什么原因，急求~谢谢！

### ISSUE THREAD

**Issue by java-xiaozhi** [alibaba/AndFix#107]
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix: loadLibrary
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix: java.lang.UnsatisfiedLinkError: Couldn't load andfix from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.gold.wulin-1.apk,libraryPath=/data/app-lib/com.gold.wulin-1]: findLibrary returned null
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix:     at java.lang.Runtime.loadLibrary(Runtime.java:365)
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix:     at java.lang.Runtime.loadLibrary(Runtime.java:355)
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix:     at com.alipay.euler.andfix.AndFix.<clinit>(AndFix.java:37)
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix:     at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix:     at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
12-16 19:33:47.286 25750-25750/com.gold.wulin E/AndFix:     at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:78)

**Comment by java-xiaozhi** [comment]
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime: FATAL EXCEPTION: main
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime: java.lang.UnsatisfiedLinkError: Native method not found: com.alipay.euler.andfix.AndFix.setup:(ZI)Z
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime:     at com.alipay.euler.andfix.AndFix.setup(Native Method)
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime:     at com.alipay.euler.andfix.AndFix.setup(AndFix.java:113)
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime:     at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime:     at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
12-17 12:06:25.998 29888-29888/com.gold.wulin E/AndroidRuntime:     at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:78)

**Comment by Comori** [comment]
应该是.so文件报错，这个项目里面只包含了armabi和x86的包，你看看你自己的项目中是不是有其他的目录，比如armabi-v7a或者arm64- v8a，如果有的话，自己重新编几个.so

**Comment by java-xiaozhi** [comment]
@Comori Thank You，I have solved！

**Comment by THEONE10211024** [comment]
@java-xiaozhi 请问你是怎么解决的？
