### ISSUE TITLE
ART下模式无法对同一个方法进行多次更新

### ISSUE THREAD

**Issue by seewhy163** [alibaba/AndFix#115]
有一个方法

```
public String getStr() {
    return "Str";
}
```

将它改成 `return "Str1";`后生成一个补丁A,，然后再改成·`return "Str2"` ，根据"Str"和"Str2"生成补丁B。

加载补丁A后是能够生效，加载完成后再加载B会crash。

上述情况的测试机型是三星galaxy s4  ，ART模式，系统是5.0.

另外小米4，4.4的系统，Dalvik模式，A补丁和B补丁都能正常加载生效。

在Genymotion的虚拟机中，机型nexus 5 ，系统4.4，如果是ART模式，A、B补丁都不能正常加载,，直接crash。Dalvik模式，所有补丁正常加载。

**Comment by qbeenslee** [comment]
应该是这样的

**Comment by lailiaomm** [comment]
我也碰到这个问题
