### ISSUE TITLE
如何使用同一份mapping文件？applymapping并没有完全全部的map，

### ISSUE THREAD

**Issue by mivanzhang** [alibaba/AndFix#121]
即使是使用了在applymapping，也会存在部分无法映射不一致（applymapping文件指定的map文件和最后生成的mapping文件存在着一定的差异），反倒是不适用这个参数（代码只有很小的改动），映射基本是一致的。这比较令我困惑，不知道大家是怎么用的？

**Comment by rambowding** [comment]
遇到相同问题，困惑中

**Comment by pzhangleo** [comment]
我发现的是，如果有方法中有内部类，即使制定mapping文件，也会导致内部类的方法的映射出现问题。

**Comment by tbruceyu** [comment]
从前一次编译的output/mapping/release/mapping.txt拷贝出来，放到一个目录下，再applymapping

**Comment by wangrunxiang** [comment]
大家有结论了么，我也同样遇到这个问题

**Comment by mivanzhang** [comment]
两个选择：1、proguard官方文档上说，改动很小的代码（andfix的改动只要不大就可以），混淆的mapping文件是相同的，
2.生成apk A的时候会生成一个mapping文件AM，在没有修改任何代码的情况下，使用AM这个applymapping 文件再生成apk B，这时伴随着apk B的mapping文件是BM，之后在没有修改任何代码的情况下，使用mapping文件BM生成apk C，这时生成的Maping文件 CM 和BM是基本相同的，只存在部分数字不相同，但是映射关系没有改变，这时可以使用apk B来作为发出的版本，BM作为保留的mapping文件

**Comment by wangrunxiang** [comment]
第一个选择和第二个选择好像差不多？@mivanzhang
针对第二个选择，
问题1：看上去好像AM和BM一样？
问题2：为什么要牵涉到三个APK？
我个人理解好像应该这样吧，我们在发版本的时候，保留这个release版本生成的mapping文件，然后发现这个版本有bug，我们需要修复，但是修复的时候修改代码后使用发版的时候的mapping文件applymapping文件来生成apk

**Comment by wangrunxiang** [comment]
顺便提一个坑，好像-printmapping指令没效果

**Comment by mivanzhang** [comment]
AM和BM要是一样的话就好了，就是因为这两个不一样，才需要在映射一次。也就是说proguard没有使用--applymapping指定mapping文件，此时生成的Mapping文件M1和使用了applymapping apply了M1这是生成的mapping文件M2，M1和M2是不相同的，存在着不少映射的差距，在proguard源码中可以看出两次生成的流程不同

**Comment by wangrunxiang** [comment]
@mivanzhang 那你是一直使用同一份mapping文件？还是说每次发版都需要做一次上述的操作？可不可以加个QQ来请教一下？我qq 578002770

**Comment by wangrunxiang** [comment]
@mivanzhang 那你是一直使用同一份mapping文件？还是说每次发版都需要做一次上述的操作？

**Comment by wangrunxiang** [comment]
@mivanzhang 顺便问一下-printmapping指令你是怎么用的，我用的不会输出mapping文件

**Comment by mivanzhang** [comment]
每次都是重新设生成mapping文件，也就是说在发布之前，需要两次打包

**Comment by wangrunxiang** [comment]
@mivanzhang 但是我自己测试，发布的时候，打包一次，然后保留下来这个mapping，然后就发版本，然后有bug的话，就applymapping来编译修复版本，生成补丁，这样子好像没问题

**Comment by mivanzhang** [comment]
那样最好啦，可能和分包以及工程的复杂度有关系吧

**Comment by wangrunxiang** [comment]
@mivanzhang 但是我这边也有分包的

**Comment by wangrunxiang** [comment]
@mivanzhang 如果一直使用一份mapping的不行的话，那打渠道包的时候咋办，一半是先发普通包更新，然后发渠道包，不是同一时间打包的

**Comment by TracyZhangLei** [comment]
用了applymapping之后，补丁包还是暴增，跟没用一样．
