### ISSUE TITLE
我是个新手，eclipse上andfix怎么使用，求教程。

### ISSUE THREAD

**Issue by neverguess** [alibaba/AndFix#159]
我是个新手，eclipse上andfix怎么使用，求教程。

**Comment by hnrainll** [comment]
可以讲andfix的aar包下载，然后修改为zip解压，将其中的jar包和so拷贝到相应的目录即可。

**Comment by LamGB** [comment]
建议你不要用eclipse了。另外，这种问题不适合在Issues里面提，自己搜一下就有解决方案了。
