### ISSUE TITLE
下次APP升级需要删除加载过的补丁包嘛

### ISSUE THREAD

**Issue by wvisible** [alibaba/AndFix#169]
如果我在2.0.0版本发布过补丁包，我在2.0.1版本的时候升级需要做什么工作吗，比如删除原来加载过的补丁还是直接发布apk不需要做任何事情呢？

**Comment by wangrunxiang** [comment]
AndFix内部已经帮你做好了，只需要在mPatchManager.init()中传入不同的参数就好了，具体可以看mPatchManager.init()的代码

**Comment by GeminiBalaBala** [comment]
init()写到appVersion变化之后删掉所有patch
