### ISSUE TITLE
app经过第三方加密平台加密之后，andfix 就不能用了，这个有好办法么？

### ISSUE THREAD

**Issue by caik13** [alibaba/AndFix#18]

**Comment by supern** [comment]
是说应用加固吗？

**Comment by caik13** [comment]
@supern  对，是应用加固，我用了一下百度的加固，然后app打开就白屏过一会就关闭了，我不知道是不是我的哪些地方没有做对，请指教一下，多谢 o(∩_∩)o

**Comment by supern** [comment]
补丁需要用加固之前的apk来做

**Comment by caik13** [comment]
@supern 非常感谢，是我之前测试的时候操作的比较混乱，听你的建议，我重新操作了一次，成功了，再次感谢

**Comment by supern** [comment]
@caik13 好的
