### ISSUE TITLE
我的工程  好几个开源库使用了JNI   有的不支持arm64   有的支持   导致一进入app 加载andfix的.so时候就报错crash了 

### ISSUE THREAD

**Issue by stevenchans** [alibaba/AndFix#188]

**Comment by JackCho** [comment]
please use 

** ndk {
        abiFilters "armeabi", "x86"
      }**

**Comment by stevenchans** [comment]
除了这个 没其他办法了吗 这样子有这些支持的 .so 就浪费了

**Comment by Amikoo** [comment]
> please use
> 
> ** ndk {
> abiFilters "armeabi", "x86"
> }**

Not acceptable. This makes other third-party .so files unusable on other platforms.

**Comment by kevenshao** [comment]
那你就自己编译andfix 的源码，来编译出各平台下的so

**Comment by supern** [comment]
已经支持arm64了
