### ISSUE TITLE
把A方法中的getI()方法copy到Fix中生成apatch，MainActivity中调用new Fix().getI();应用patch崩溃

### ISSUE THREAD

**Issue by jbg168** [alibaba/AndFix#19]
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.euler.andfix, PID: 6964
E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getI()I in class Lcom/euler/test/Fix_CF; or its super classes (declaration of 'com.euler.test.Fix_CF' appears in /data/user/0/com.euler.andfix/files/apatch/out.apatch)
E AndroidRuntime: 	at com.euler.andfix.MainActivity_CF.onCreate(MainActivity.java:45)
E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I Process : Sending signal. PID: 6964 SIG: 9
I ActivityManager: Process com.euler.andfix (pid 6964) has died

**Comment by supern** [comment]
补丁文件发我一下。
你这是新增方法么？

**Comment by jbg168** [comment]
是新增方法：
apkpatch执行时日志
add modified Method:V  onCreate(Landroid/os/Bundle;)  in Class:Lcom/euler/andfix/MainActivity;
add modified Method:Ljava/lang/String;  a(Ljava/lang/String;)  in Class:Lcom/euler/test/A;
add modified Method:I  b(Ljava/lang/String;Ljava/lang/String;)  in Class:Lcom/euler/test/Fix;
add new Method:I  getI()  in Class:Lcom/euler/test/Fix;
补丁文件中Fix_CF.smali：
.class public Lcom/euler/test/Fix_CF;
.super Ljava/lang/Object;
.source "Fix.java"


# static fields
.field static i:I

.field private static o:Lcom/euler/test/O;


# instance fields
.field s:Ljava/lang/String;


# direct methods
.method static constructor <clinit>()V
    .locals 2

    .prologue
    .line 30
    new-instance v0, Lcom/euler/test/O;

    const-string v1, "fix"

    invoke-direct {v0, v1}, Lcom/euler/test/O;-><init>(Ljava/lang/String;)V

    sput-object v0, Lcom/euler/test/Fix_CF;->o:Lcom/euler/test/O;

    .line 31
    const/16 v0, 0xb

    sput v0, Lcom/euler/test/Fix_CF;->i:I

    return-void
.end method

.method public constructor <init>()V
    .locals 1

    .prologue
    .line 28
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 29
    const-string v0, "s"

    iput-object v0, p0, Lcom/euler/test/Fix_CF;->s:Ljava/lang/String;

    return-void
.end method

.method public static a(Ljava/lang/String;)Ljava/lang/String;
    .locals 2
    .param p0, "str"    # Ljava/lang/String;

    .prologue
    .line 34
    const-string v0, "qq"

    invoke-static {v0, p0}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 35
    const-string v0, "euler"

    const-string v1, "fix succes"

    invoke-static {v0, v1}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I

    .line 36
    const-string v0, "b"

    return-object v0
.end method

.method private c()Ljava/lang/String;
    .locals 1

    .prologue
    .line 48
    const-string v0, "a"

    return-object v0
.end method


# virtual methods
.method public b(Ljava/lang/String;Ljava/lang/String;)I
    .locals 3
    .param p1, "s1"    # Ljava/lang/String;
    .param p2, "s2"    # Ljava/lang/String;
    .annotation runtime Lcom/alipay/euler/andfix/annotation/MethodReplace;
        method = "b"
        clazz = "com.euler.test.Fix"
    .end annotation

    .prologue
    .line 40
    const-string v0, "euler"

    invoke-static {v0, p1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    .line 41
    const-string v0, "euler"

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    sget v2, Lcom/euler/test/Fix;->i:I

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v1

    const-string v2, "=="

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-direct {p0}, Lcom/euler/test/Fix_CF;->c()Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->e(Ljava/lang/String;Ljava/lang/String;)I

    .line 42
    const-string v0, "euler"

    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    const-string v2, "fix succes"

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    iget-object v2, p0, Lcom/euler/test/Fix_CF;->s:Ljava/lang/String;

    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v1

    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    invoke-static {v0, v1}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I

    .line 43
    const-string v0, "euler"

    sget-object v1, Lcom/euler/test/Fix;->o:Lcom/euler/test/O;

    iget-object v1, v1, Lcom/euler/test/O;->s:Ljava/lang/String;

    invoke-static {v0, v1}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I

    .line 44
    const/16 v0, 0x2710

    return v0
.end method

.method public getI()I
    .locals 1

    .prologue
    .line 52
    sget v0, Lcom/euler/test/Fix;->i:I

    return v0
.end method

**Comment by supern** [comment]
@jbg168 目前不支持单纯的新增方法

**Comment by LuckZhang** [comment]
@jbg168  这个问题最终如何解决的，能否帮忙解答一下，谢谢！

**Comment by AnotherSkyBoy** [comment]
不可以直接修改Acitivity中的方法吧，activity在menifest里面声明了，热修复后的类是映射为xxx_CF，是没有在menifest中声明的
