### ISSUE TITLE
1+ 手机 1代闪退.

### ISSUE THREAD

**Issue by xiebaiyuan** [alibaba/AndFix#191]
0 E/AndFix: loadLibrary
                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hahaha.hahah-2/base.apk"],nativeLibraryDirectories=[/data/app/com.hahaha.hahah-2/lib/arm, /data/app/com.hahaha.hahah-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libandfix.so"

**Comment by soMeJordan** [comment]
请问这个问题解决了吗

**Comment by kevenshao** [comment]
如果用compile加载andfix, 目前andfix只有armeabi和x86架构的so，其它的还没有，如果用的AndroidStudio，可以把打包后的APK解开看看，可能你打包时也包含了armeabi-v7和64位架构的，而这些里面并没有对应的so，所以出现问题。 可以配置一下，打包时只打包armeabi和x86这两个架构类型。

**Comment by supern** [comment]
@kevenshao 新版本支持了
