### ISSUE TITLE
没搞懂版本号

### ISSUE THREAD

**Issue by moter** [alibaba/AndFix#193]
PatchManager.init（）这个作用是什么
两个bug，分两次修复，第一次修复第一个bug后制作apatch可以加载更新。稍后再之前的基础上再制作第二个bug的apatch。加载后没有修复第二个bug。感觉这儿有点混乱。求大神解释下

**Comment by hellokugo** [comment]
回答下init的作用。
前面好理解，主要是判断指定存放的patch是否存在和文件夹之类的判断；之后再SharedPreferences保存的apk版本信息，注意这里有两个判断，二者满足其一都要清空patch目录：

---ver为空，即手机本身不存在该apk，新安装的apk不可能一开始就有patch文件吧？
---保存的ver和传入的version不一致，场景是，假如你的apk在1.0做patch修复（当然可以加载多个.patch文件），在你决定要做重大版本更新的时候（这里假如你准备发2.0），这时候你2.0的apk应该是已经包含修复1.0 bug的代码，这时候就不需要1.0所要的修复.patch文件，所以在检查保存版本和你传入版本不一致就会做清空操作。

至于你下面说的两个patch修复没有实现，要详细说明下操作，正常情况下应该是可以的。
