### ISSUE TITLE
5.0以上动态加载patch出现anr

### ISSUE THREAD

**Issue by superLY91** [alibaba/AndFix#198]
5.0以上系统调用addPatch()动态加载patch，当进入patch修改的界面时出现nar。

**Comment by w4lle** [comment]
同样碰到这个问题
第一次加载patch没问题，第二次进入出现调用修复的方法时anr
虽然还不知道具体的原因是什么
解决办法：
patchManager.loadPatch(); 延后加载，比如请求patch请求后再加载。
#82

**Comment by TracyZhangLei** [comment]
坑啊

**Comment by zimo2013** [comment]
感觉问题还有很多

**Comment by supern** [comment]
已经修复

**Comment by TracyZhangLei** [comment]
@supern 最近几次的更新都验证过么？

**Comment by supern** [comment]
@TracyZhangLei 测试过，而且在阿里内部同步灰度

**Comment by TracyZhangLei** [comment]
@supern 好的，谢谢

**Comment by leonzhuhi** [comment]
@supern com.alipay.euler:andfix:0.5.0@aar 的包，在5.0以上的 手机首次进入修改bug的界面还是卡死，请问你们修改的版本在那个以上？是修改JNI里面的东西了吗？还是其他的
