### ISSUE TITLE
apkpatch的linux脚本中是不是存在删除文件的指令？！！

### ISSUE THREAD

**Issue by arge128** [alibaba/AndFix#20]
为什么我跑了一下这个脚本之后，我的目录下面的文件都删了很多？为什么readme中不写清楚！

**Comment by supern** [comment]
会初始化out目录，保证输出是干净的

**Comment by arge128** [comment]
你知道吗，我设置的out目录是~，现在要哭死了

**Comment by MrFuFuFu** [comment]
你得在新文件夹中输出 out 目录，不然，是会删除完的。看到这个，我表示深深的同情。。。。。。但是。。。请先让我大笑三声。。。哈哈哈哈哈哈哈哈哈哈。。因为我也发生了这样的事情。但幸好是在一个比较小的子文件夹下！

**Comment by caomaocao** [comment]
初始化out目录....

**Comment by cleverlgsliu** [comment]
哈哈~

**Comment by pinguo-marui** [comment]
同情LZ，是有这个问题，我也以为会默认在新建文件夹输出，还好我先放的文件夹没有删除权限，然后看到了remove失败的消息，果断放到temp下了（哈哈哈哈）...

**Comment by supern** [comment]
@arge128  非常抱歉，我们接下来会把apkpatch这块坐下修改

**Comment by supern** [comment]
@arge128  已经更新，把删除操作给去了

**Comment by JuanbingTeam** [comment]
Thanks God!!!!!  还好我只是被删掉了几个文件

**Comment by arge128** [comment]
@supern 多谢了

**Comment by birdman2005** [comment]
为何会在有差别的类后面加上_CF，我的差别是activity
