### ISSUE TITLE
'Letv/乐视超级手机1/x600:5.0.2

### ISSUE THREAD

**Issue by zengbobo0805** [alibaba/AndFix#200]
AndFixManager replaceMethod 报错
/**********************************************************************************************************/
06-06 09:49:53.405 7879-7879/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xcbd00012cf8010 in tid 7879 (m.icaikee.xrzgp)
06-06 09:49:53.405 260-260/? D/AEE/AED: $===AEE===AEE===AEE===$
06-06 09:49:53.405 260-260/? D/AEE/AED: p 0 poll events 1 revents 0
06-06 09:49:53.405 260-260/? D/AEE/AED: not know revents:0
06-06 09:49:53.405 260-260/? D/AEE/AED: p 1 poll events 1 revents 0
06-06 09:49:53.405 260-260/? D/AEE/AED: not know revents:0
06-06 09:49:53.405 260-260/? D/AEE/AED: p 2 poll events 1 revents 1
06-06 09:49:53.405 260-260/? D/AEE/AED: aed_main_fork_worker: generator 0x7f8611c0e0, worker 0x7feb12e5f0, recv_fd 14
06-06 09:49:53.406 260-260/? D/AEE/AED: p 3 poll events 1 revents 0
06-06 09:49:53.406 260-260/? D/AEE/AED: not know revents:0
06-06 09:49:53.406 7904-7904/? I/AEE/AED: handle_request(14)
06-06 09:49:53.406 7904-7904/? I/AEE/AED: check process 7879 name:m.icaikee.xrzgp
06-06 09:49:53.406 7904-7904/? I/AEE/AED: tid 7879 abort msg address is:0x0000000000000000 si_code is:1 (request from 7879:10280)
06-06 09:49:53.406 7904-7904/? I/AEE/AED: BOOM: pid=7879 uid=10280 gid=10280 tid=7879
06-06 09:49:53.407 7904-7904/? I/AEE/AED: [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 7879, tid: 7879, name: m.icaikee.xrzgp  >>> com.icaikee.xrzgp <<<
06-06 09:49:53.470 7904-7904/? I/AEE/AED: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-06 09:49:53.470 7904-7904/? I/AEE/AED: Build fingerprint: 'Letv/乐视超级手机1/x600:5.0.2/ABXCNOP5501304131S/67:user/release-keys'
06-06 09:49:53.470 7904-7904/? I/AEE/AED: Revision: '0'
06-06 09:49:53.470 7904-7904/? I/AEE/AED: ABI: 'arm64'
06-06 09:49:53.470 7904-7904/? I/AEE/AED: pid: 7879, tid: 7879, name: m.icaikee.xrzgp  >>> com.icaikee.xrzgp <<<
06-06 09:49:53.470 7904-7904/? I/AEE/AED: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xcbd00012cf8010
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x0   12d8f00012ddb300  x1   12cbd00012cf8000  x2   0000000000000001  x3   0000007f8ce7630c
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x4   0000000000000000  x5   0000007f8ce76308  x6   0000000000000000  x7   0000000000430000
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x8   0000000000000000  x9   fb08f4d8bde8bbcc  x10  0000000000000000  x11  0000000000430000
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x12  0000000000550000  x13  0000000000430000  x14  0000000000000000  x15  0000007f8cdfa000
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x16  0000007f8cdfd470  x17  000000000000002e  x18  0000007f8cd48000  x19  0000000000000036
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x20  0000007f8b793e4c  x21  0000007f8ce97000  x22  0000000012c6f200  x23  0000000012d6d1e0
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x24  0000000012c18000  x25  0000000012c6fdd0  x26  0000000012cbc0e0  x27  0000000012caabc0
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     x28  0000000012c6f200  x29  0000000000000020  x30  0000007f8b794238
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     sp   0000007ff9a5bc90  pc   0000007f8b79424c  pstate 0000000060000000
06-06 09:49:53.480 7904-7904/? I/AEE/AED: backtrace:
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     #00 pc 000000000000124c  /data/app/com.icaikee.xrzgp-2/lib/arm64/libandfix.so (replace_5_0(_JNIEnv*, _jobject*, _jobject*)+68)
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     #01 pc 0000000000001118  /data/app/com.icaikee.xrzgp-2/lib/arm64/libandfix.so
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     #02 pc 0000000000000e84  /data/app/com.icaikee.xrzgp-2/lib/arm64/libandfix.so
06-06 09:49:53.480 7904-7904/? I/AEE/AED:     #03 pc 0000000000301998  /data/dalvik-cache/arm64/data@app@com.icaikee.xrzgp-2@base.apk@classes.dex
06-06 09:49:53.585 769-1304/? D/CSLegacyTypeTracker: getNetworkForType type 1
06-06 09:49:53.585 769-1304/? D/CSLegacyTypeTracker: getNetworkForType type 1
06-06 09:49:53.585 769-1304/? D/CSLegacyTypeTracker: getNetworkForType type 1
06-06 09:49:53.585 769-1304/? D/ConnectivityService: getActiveNetworkInfo:[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "xrz-5G", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]/1000
06-06 09:49:53.586 769-1304/? I/NetworkPolicy: real time onreceive...cur_kb:0.00b/s
06-06 09:49:53.586 769-1304/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1414 com.android.server.net.NetworkPolicyManagerService$4.handleMessage:654 android.os.Handler.dispatchMessage:111 android.os.Looper.loop:194 android.os.HandlerThread.run:61 
06-06 09:49:53.586 769-1304/? V/ActivityManager: Broadcast: Intent { act=android.intent.action.UPDATE_REALTIME_SPEED flg=0x10 (has extras) } ordered=false userid=0 callerApp=ProcessRecord{37c537fd 769:system/1000, isShadow:false}
06-06 09:49:53.587 1043-1043/? D/PhoneStatusBar: refreshNetSpeed:0.00b/s
06-06 09:49:53.602 6206-6206/? W/ADB_SERVICES: create_local_service_socket() name=shell:cat /proc/7751/stat
06-06 09:49:53.602 6206-6206/? W/ADB_SERVICES: service_to_fd() name=shell:cat /proc/7751/stat
06-06 09:49:53.603 6206-6206/? W/ADB_SERVICES: read_meminfo() mem_free=515048
06-06 09:49:53.603 6206-6206/? W/ADB_SERVICES: create_subproc ret_fd=22 pid=7905
06-06 09:49:53.603 6206-6206/? W/ADB_SERVICES: LS(315): bound to 'shell:cat /proc/7751/stat' via 22
06-06 09:49:53.604 7905-7905/? W/ADB_SERVICES: adb: unable to update oom_score_adj
06-06 09:49:53.608 6206-6206/? D/ADB_SERVICES:  closing because is_eof=1 r=-1 s->fde.force_eof=0
06-06 09:49:53.608 6206-6206/? W/ADB_SERVICES: entered. LS(315) fd=22
06-06 09:49:53.611 769-1092/? D/PerfServiceManager: [PerfService] notifyFrameUpdate - bDuringTouchBoost:false 
06-06 09:49:53.628 246-246/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:2.515796,dur:1192.47,max:409.46,min:390.63
06-06 09:49:53.629 275-436/? D/AALService: enableAALEvent: 0 -> 1
06-06 09:49:53.630 275-436/? D/AALService: Output backlight = 577/1023
06-06 09:49:53.638 275-436/? D/AALService: Output backlight = 578/1023
06-06 09:49:53.640 6206-6206/? W/ADB_SERVICES: create_local_service_socket() name=shell:cat /proc/stat
06-06 09:49:53.640 6206-6206/? W/ADB_SERVICES: service_to_fd() name=shell:cat /proc/stat
06-06 09:49:53.640 6206-6206/? W/ADB_SERVICES: read_meminfo() mem_free=514536
06-06 09:49:53.641 6206-6206/? W/ADB_SERVICES: create_subproc ret_fd=22 pid=7906
06-06 09:49:53.641 6206-6206/? W/ADB_SERVICES: LS(316): bound to 'shell:cat /proc/stat' via 22
06-06 09:49:53.641 7906-7906/? W/ADB_SERVICES: adb: unable to update oom_score_adj
06-06 09:49:53.648 6206-6206/? D/ADB_SERVICES:  closing because is_eof=1 r=1 s->fde.force_eof=0
06-06 09:49:53.648 6206-6206/? W/ADB_SERVICES: entered. LS(316) fd=22
06-06 09:49:53.655 275-436/? D/AALService: enableAALEvent: 1 -> 0
06-06 09:49:53.989 1461-1536/? D/cell strength: ===== cell singal strength changed : 20
06-06 09:49:53.995 769-1680/? V/ActivityManager: Broadcast sticky: Intent { act=android.intent.action.SIG_STR flg=0x20000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{37c537fd 769:system/1000, isShadow:false}
06-06 09:49:54.021 769-1641/? D/PerfServiceManager: [PerfService] notifyFrameUpdate - bDuringTouchBoost:false 
06-06 09:49:54.039 275-436/? D/AALService: enableAALEvent: 0 -> 1
06-06 09:49:54.040 275-436/? D/AALService: Output backlight = 579/1023
06-06 09:49:54.048 275-436/? D/AALService: enableAALEvent: 1 -> 0
06-06 09:49:54.052 769-769/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 14 num clients 15
06-06 09:49:54.053 769-769/? E/WifiTrafficPoller:  packet count Tx=1268 Rx=1337
06-06 09:49:54.089 3170-3192/? I/memoryInfo: totalMemory MB = 1
06-06 09:49:54.309 6206-6206/? W/ADB_SERVICES: create_local_service_socket() name=jdwp:7879
06-06 09:49:54.309 6206-6206/? W/ADB_SERVICES: service_to_fd() name=jdwp:7879
06-06 09:49:54.310 6206-6206/? W/ADB_SERVICES: looking for pid 7879 in JDWP process list return fds0(22) fds1(23)
06-06 09:49:54.310 6206-6206/? W/ADB_SERVICES: LS(317): bound to 'jdwp:7879' via 22
06-06 09:49:54.310 6206-6206/? W/ADB_SERVICES: trying to write to JDWP socket=20 pid=7879 count=1 out_fds=23
06-06 09:49:54.430 769-1092/? D/PerfServiceManager: [PerfService] notifyFrameUpdate - bDuringTouchBoost:false 
06-06 09:49:54.436 246-431/? I/BufferQueueProducer: [StatusBar](this:0x7f97fb6000,id:9,api:1,p:1043,c:246) queueBuffer: fps=2.47 dur=1214.59 max=412.68 min=392.57
06-06 09:49:54.448 275-436/? D/AALService: enableAALEvent: 0 -> 1
06-06 09:49:54.450 275-436/? D/AALService: Output backlight = 580/1023
06-06 09:49:54.457 275-436/? D/AALService: Output backlight = 581/1023
06-06 09:49:54.474 275-436/? D/AALService: enableAALEvent: 1 -> 0
06-06 09:49:54.550 769-803/? I/ANRManager: updateProcessStats
06-06 09:49:54.839 246-246/? I/SurfaceFlinger: [Built-in Screen (type:0)] fps:2.477139,dur:1211.07,max:409.89,min:392.05
06-06 09:49:54.841 275-436/? D/AALService: enableAALEvent: 0 -> 1
06-06 09:49:54.843 275-436/? D/AALService: Output backlight = 582/1023
06-06 09:49:54.849 275-436/? D/AALService: enableAALEvent: 1 -> 0
06-06 09:49:55.055 769-769/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 14 num clients 15
06-06 09:49:55.056 769-769/? E/WifiTrafficPoller:  packet count Tx=1268 Rx=1337
06-06 09:49:55.089 3170-3192/? I/memoryInfo: totalMemory MB = 1
06-06 09:49:55.231 769-1394/? D/PerfServiceManager: [PerfService] notifyFrameUpdate - bDuringTouchBoost:false 
06-06 09:49:55.250 275-436/? D/AALService: enableAALEvent: 0 -> 1
06-06 09:49:55.251 275-436/? D/AALService: Output backlight = 583/1023
06-06 09:49:55.258 275-436/? D/AALService: enableAALEvent: 1 -> 0
06-06 09:49:55.385 284-284/? I/thermal_repeater: oh, queryMdThermalInfo (0)Bad file number
06-06 09:49:55.394 284-284/? I/thermal_repeater: [recvMdThermalInfo] ret=25, strLen=127,  1, 32767,,, -1, 32767, 2
**06-06 09:49:55.475 769-1070/? E/NativeCrashListener: Exception dealing with report
                                                     android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                         at libcore.io.Posix.readBytes(Native Method)
                                                         at libcore.io.Posix.read(Posix.java:147)
                                                         at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                         at android.system.Os.read(Os.java:364)
                                                         at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                         at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)**

**Comment by supercoeus** [comment]
同样的问题，不知道解决了吗

**Comment by supern** [comment]
@supercoeus  @zengbobo0805 试试新版本
