### ISSUE TITLE
Android5.0, ArtMethod结构体有问题！

### ISSUE THREAD

**Issue by jluysf** [alibaba/AndFix#210]
对比一下这个, android5.0.0_r2 [art_method.h]:(http://androidxref.com/5.0.0_r2/xref/art/runtime/mirror/art_method.h#482)
HeapReference<Class> **declaring_class_;**
HeapReference<ObjectArray<ArtMethod>> **dex_cache_resolved_methods_;**
HeapReference<ObjectArray<Class>> **dex_cache_resolved_types_;**
HeapReference<ObjectArray<String>> **dex_cache_strings_;**
uint64_t **entry_point_from_interpreter_;**
uint64_t **entry_point_from_jni_;**
uint64_t **entry_point_from_quick_compiled_code_;**
uint64_t **gc_map_;**
uint32_t **access_flags_;**
uint32_t **dex_code_item_offset_;**
uint32_t **dex_method_index_;**
uint32_t **method_index_;**
...
恐怕会产生一些诡异的问题.

**Comment by supern** [comment]
已经修复，谢谢
