### ISSUE TITLE
提示说找不到so文件

### ISSUE THREAD

**Issue by wzsxlh** [alibaba/AndFix#213]
androidstudio环境下

之前写了demo只用gradle加载jar包，是没有问题的
现在移到项目上就报这个错误，我在jniLibs文件夹下面放了so文件，然后移除gradle依赖，添加libs包，还是不行。

跪求解决方法！！

具体错误：
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kpsns.hebeiykp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.kpsns.hebeiykp-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libandfix.so"

**Comment by supern** [comment]
是64位机器吗

**Comment by wzsxlh** [comment]
是的。

**Comment by supern** [comment]
@wzsxlh 用新版本试试

**Comment by wzsxlh** [comment]
好的。其实16年五月多的时候我重新试了一下，集成到项目里就可以用了。希望大神继续维护这个库。

**Comment by supern** [comment]
@wzsxlh 嗯，好的，会维护的
