### ISSUE TITLE
魅族note4使用andfix打补丁时崩溃

### ISSUE THREAD

**Issue by yueyeweiming** [alibaba/AndFix#215]
将项目里的arm64-v8a下的so文件copy到了工程中.
报错信息如下
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8000212cbb010 in tid 15501

**Comment by yueyeweiming** [comment]
感觉是这个so文件有问题,只能先删除arm64-v8a文件夹了,但是这样还影响了其他库的使用.

**Comment by congtaowang** [comment]
目测使用了andfix的app都只支持了armeabi和x86两种cpu架构

**Comment by shijia109** [comment]
note4？啥时候出的

**Comment by supern** [comment]
arm64，6.0的已经修复

**Comment by cococa** [comment]
@supern 想问下，阿里内部项目有用到andfix 吗，还有你说7.0在适配了，大概什么时候可以发？

**Comment by supern** [comment]
@cococa 阿里的app基本都用，大概要双十一之后了
