### ISSUE TITLE
apkpatch 使用androidstudio的keystore打patch的时候出问题

### ISSUE THREAD

**Issue by 952010613** [alibaba/AndFix#216]
把andfixdemo 导入Androidstudio编译生成两个 apk文件后
执行 apkpatch.sh -f app-release2.apk -t app-release.apk -o keystore/ –k keystore/debug.jks –p 888888 -a andfix -e 888888  时 出现问题

keystore/debug.jks 是androidstudio 签名的格式， 有人碰到吗？

**Comment by 952010613** [comment]
提示 ： 用法不对

ApkPatch v1.0.3 - a tool for build/merge Android Patch file (.apatch).
Copyright 2015 supern lee <sanping.li@alipay.com>

usage: apkpatch -f <new> -t <old> -o <output> -k <keystore> -p <***> -a <alias> -e <***>
 -a,--alias <alias>     alias.
 -e,--epassword <***>   entry password.
 -f,--from <loc>        new Apk file path.
 -k,--keystore <loc>    keystore path.
 -n,--name <name>       patch name.
 -o,--out <dir>         output dir.
 -p,--kpassword <***>   keystore password.
 -t,--to <loc>          old Apk file path.

usage: apkpatch -m <apatch_path...> -k <keystore> -p <***> -a <alias> -e <***>
 -a,--alias <alias>     alias.
 -e,--epassword <***>   entry password.
 -k,--keystore <loc>    keystore path.
 -m,--merge <loc...>    path of .apatch files.
 -n,--name <name>       patch name.
 -o,--out <dir>         output dir.
 -p,--kpassword <***>   keystore password.

**Comment by smallsilver** [comment]
***自从更新android studio 版本，我生成出来的apatch文件不可用，原来一直可用。***

*android studio、java版本*

``java
Android Studio 2.2 Preview 3
Build #AI-145.2949926, built on June 7, 2016
JRE: 1.8.0_76-release-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
``

*apkpatch 命令*

``java
./apkpatch.sh -f 2.3.4_n.apk -t 2.3.4.apk -o ./ -k my.keystore -p xx -a xxx -e xxx
``
可以生成出.apatch,diff.dex,但是文件很小。也不可用。
smali文件夹下面没有文件。

_**如何解决？**_
