### ISSUE TITLE
加载So发生Crash，在5.0以及6.0的手机上发生

### ISSUE THREAD

**Issue by kylexjk** [alibaba/AndFix#220]
![image](https://cloud.githubusercontent.com/assets/15087881/17480972/283ae22c-5dad-11e6-80fa-c1d61cd81b49.png)

从git上面复制的so库，能加载到指定的库，在demo程序里面可以运行，换了一个项目之后（可能代码添加的比较多了），相同的代码运行报错如上，是不是和权限有关呢？

**Comment by kylexjk** [comment]
结帖：在使用的过程中，使用了其他的so库导致崩溃。在项目中，只使用 "armeabi","x86"2个库，和Andfix保持一直。不知道为啥使用官网lib下的其他so文件会报错，不使用也算是饮鸩止渴的一种做法吧

**Comment by ityancs** [comment]
删除jni下的其他库，只留下armeabi和x86应该可以
