### ISSUE TITLE
Galaxy S7 edge ,Android 6.0.1 无效

### ISSUE THREAD

**Issue by lasttimes** [alibaba/AndFix#223]
在 nexus5,Android 6.0  上可以，但在Galaxy S7 edge ,Android 6.0.1 无效，也没报错

**Comment by lasttimes** [comment]
看了下代码是 Compat.isSupportSDKVersion 里限制了版本为2.3 到 6.0。
建议至少加个警告。

**Comment by supern** [comment]
好的，7.0在适配中

**Comment by supern** [comment]
@lasttimes 新版本
