### ISSUE TITLE
有兼容性问题啊，华为p8青春版（移动）这台手机不能热更新

### ISSUE THREAD

**Issue by tjjlhst** [alibaba/AndFix#226]
试了几台手机都可以热更新修复bug，但是华为p8青春版（移动版）不能修复，甚至安装了补丁包后，每次打开app都闪退，这是怎么回事？华为p8青春版的CPU为海思麒麟 620

**Comment by tjjlhst** [comment]
系统版本为5.0.2，emui 3.1

**Comment by crownbox** [comment]
看下CPU是不是64位的，可能是这个原因

**Comment by supern** [comment]
@tjjlhst 升级新版本试试

**Comment by tjjlhst** [comment]
是最新版本的了，0.4.0。CPU是64位，但是指令集是AArch64 Processor rev 3 (aarch64)，用了另一台能正常打补丁的华为p7（cpu为910）和nexus5，它们的指令集都是ARMv7 Processor rev 3 (v7l)

**Comment by supern** [comment]
@tjjlhst 0.4.1版本

**Comment by tjjlhst** [comment]
@supern @crownbox 感谢阿里大神，p8已经适配成功，是64位处理器的问题。谢谢大神们的奉献和分享
