### ISSUE TITLE
How to run AndFixDemo?

### ISSUE THREAD

**Issue by fhlkm** [alibaba/AndFix#228]
After I open  the project by Android studio. It looks like a library project.

How can I run "AndFixDemo"?

Thanks

**Comment by supern** [comment]
1. Import samplesI/AndFixDemo to your IDE, append AndFixDemo dependencies with AndFix(library project or aar).
2. Build project, save the package as 1.apk, and then install on device/emulator.
3. Modify com.euler.test.A, references com.euler.test.Fix.
4. Build project, save the package as 2.apk.
5. Use apkpatch tool to make a patch.
6. Rename the patch file to out.apatch, and then copy it to sdcard.
7. Run 1.apk and view log.
