### ISSUE TITLE
ClassNotFoundException 无法捕捉

### ISSUE THREAD

**Issue by atxxiang3** [alibaba/AndFix#231]
本地有个混淆过的APK的补丁，然后直接安装DEBUG版本的APK，加载补丁，发现ClassNotFoundException 无法捕捉。。。

**Comment by supern** [comment]
@atxxiang3  混淆问题吧，保持混淆一致吧，参考 applymapping

**Comment by atxxiang3** [comment]
那如果本来就没有这个类，然后误加载了这个类相关补丁，不就还是崩溃嘛

**Comment by supern** [comment]
@atxxiang3 嗯，你的意思是误加载补丁了是吧

**Comment by atxxiang3** [comment]
对啊，这种情况可不可以不让应用崩溃啊

**Comment by qiebixuefu12345** [comment]
我也遇到这种情况,有什么好的办法吗?解决了吗
