### ISSUE TITLE
RuntimeException when use apkpatch

### ISSUE THREAD

**Issue by ChyilyHsu** [alibaba/AndFix#24]
Hi,

Use apkpatch to generate patch file, it will throw RuntimeException, following is log:
============================================================================
add modified Method:V  a()  in Class:Lcom/trendmicro/safesync/core/provider/bg;
add new Method:V  a(Lorg/json/JSONObject;)  in Class:Lcom/trendmicro/safesync/core/provider/bw;
add new Method:V  c(I)  in Class:Lcom/trendmicro/safesync/core/provider/bw;
add modified Method:V  a()  in Class:Lcom/trendmicro/safesync/core/provider/bw;
java.lang.RuntimeException: can,t add new Field:m(Lcom/trendmicro/safesync/core/provider/ak;), in class :Lcom/trendmicro/safesync/core/provider/bx;
	at com.euler.patch.diff.DiffInfo.addAddedFields(DiffInfo.java:77)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:132)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97) 
============================================================================

**Comment by ChyilyHsu** [comment]
I find the code in DiffInfo.class:

public void addAddedFields(DexBackedField field) {
    this.addedFields.add(field);
    throw new RuntimeException("can,t add new Field:" + 
      field.getName() + "(" + field.getType() + "), " + "in class :" + 
      field.getDefiningClass());
}

Why throw exception after addedFields?

**Comment by supern** [comment]
because not support add fields now

**Comment by gdgm123** [comment]
@supern  替换方法的时候是在载入补丁的时候替换，还是在运行存在bug原方法的时候替换

**Comment by gdgm123** [comment]
@supern apkpatch 1.0.3生成补丁时出现这个异常，紧急求助
![image](https://cloud.githubusercontent.com/assets/8435690/10092503/a8d182f8-6379-11e5-9fcc-47623e243afb.png)

**Comment by gdgm123** [comment]
@supern 
混淆之后就出现这个错误?如何解决？求帮助
![image](https://cloud.githubusercontent.com/assets/8435690/10096312/131ea4d2-63a3-11e5-9915-8a5858244c31.png)
