### ISSUE TITLE
java.lang.UnsatisfiedLinkError:错误

### ISSUE THREAD

**Issue by just-for-you** [alibaba/AndFix#244]
一旦添加依赖（compile 'com.alipay.euler:andfix:0.5.0@aar'）后生成的APK就出现java.lang.UnsatisfiedLinkError:错误。找不到对应的so文件，so文件都是armeabi架构的

**Comment by just-for-you** [comment]
求大神指教呀

**Comment by just-for-you** [comment]
具体信息如下：java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ifreetalk.ftalk-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ifreetalk.ftalk-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libNetCore.so"

**Comment by supern** [comment]
@just-for-you 你的libNetCore是不是没有arm64的啊

**Comment by just-for-you** [comment]
恩，没有64位的，仅仅有armeabi，我最后加了句
ndk {
    abiFilters "armeabi"
}
可以正常编译过了，这样有什么风险吗？

**Comment by supern** [comment]
最好都有arm64的，要不不支持arm64的啊

**Comment by just-for-you** [comment]
恩，好的，多谢提醒
