### ISSUE TITLE
java.lang.IncompatibleClassChangeError？

### ISSUE THREAD

**Issue by just-for-you** [alibaba/AndFix#247]
安装生成的patch补丁后，出现这样的问题，java.lang.IncompatibleClassChangeError: Couldn't find com.alipay.euler.andfix.annotation.MethodReplace.clazz，急求大神指教下，等着发版本呢？

**Comment by just-for-you** [comment]
已经解决，主要是混淆有问题

**Comment by ContinueCoding** [comment]
@just-for-you 请问具体是怎么解决的？我也遇到了这个问题。是issue 72中那位说的那样吗？
