### ISSUE TITLE
java.lang.IllegalAccessError: interface not accessible

### ISSUE THREAD

**Issue by kevinet** [alibaba/AndFix#25]
java.lang.IllegalAccessError: interface not accessible
            at dalvik.system.DexFile.defineClassNative(Native Method)
            at dalvik.system.DexFile.defineClass(DexFile.java:222)
            at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
            at dalvik.system.DexFile.loadClass(DexFile.java:204)
            at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:169)
            at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:203)
            at com.wecook.common.modules.hotfix.HotFixTools.setup(HotFixTools.java:40)
            at com.wecook.common.modules.ModuleManager.registerAllModules(ModuleManager.java:104)
            at com.wecook.common.app.BaseApp.onCreate(BaseApp.java:40)
            at cn.wecook.app.WecookApp.onCreate(WecookApp.java:38)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4574)
            at android.app.ActivityThread.access$1500(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5332)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by supern** [comment]
修改了接口？

**Comment by kevinet** [comment]
没有修改，只是单纯的修改一个Toast的弹出。patch工具列出了很多类的变化，但其实我就修改了一个类。

**Comment by kevinet** [comment]
贴上更详细的日志：


vm is: dalvik , apilevel is: 19
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z24dvmComputeMethodArgsSizePK6Method = 0x40d57c39
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z13dvmCallMethodP6ThreadPK6MethodP6ObjectP6JValuez = 0x40d80ad1
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z25dexProtoGetParameterCountPK8DexProto = 0x40e4d803
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ dvmAllocArrayByClass = 0x40d8e491
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z15dvmBoxPrimitive6JValueP11ClassObject = 0x40d99521
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z21dvmFindPrimitiveClassc = 0x40d91145
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ dvmReleaseTrackedAlloc = 0x40d6e899
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z17dvmCheckExceptionP6Thread = 0x40d57d01
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z15dvmGetExceptionP6Thread = 0x40d57cf9
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z17dvmFindArrayClassPKcP6Object = 0x40d8e961
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z28dvmCreateReflectMethodObjectPK6Method = 0x40d98e35
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z21dvmGetBoxedReturnTypePK6Method = 0x40d996d9
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z17dvmUnboxPrimitiveP6ObjectP11ClassObjectP6JValue = 0x40d995a5
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z20dvmDecodeIndirectRefP6ThreadP8_jobject = 0x40d5b269
09-22 18:38:39.568  22157-22157/cn.wecook.app D/AndFix﹕ _Z13dvmThreadSelfv = 0x40d6afd1
09-22 18:38:39.576  22157-22157/cn.wecook.app D/OpenSSLLib﹕ OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:142;Function:ASN1_get_object
09-22 18:38:39.585  22157-22157/cn.wecook.app D/dalvikvm﹕ create interp thread : stack size=128KB
09-22 18:38:39.585  22157-22157/cn.wecook.app D/dalvikvm﹕ create new thread
09-22 18:38:39.585  22157-22157/cn.wecook.app D/dalvikvm﹕ new thread created
09-22 18:38:39.585  22157-22157/cn.wecook.app D/dalvikvm﹕ update thread list
09-22 18:38:39.585  22157-22227/cn.wecook.app D/dalvikvm﹕ threadid=12: interp stack at 0x7922d000
09-22 18:38:39.585  22157-22227/cn.wecook.app D/dalvikvm﹕ threadid=12: created from interp
09-22 18:38:39.585  22157-22157/cn.wecook.app D/dalvikvm﹕ start new thread
09-22 18:38:39.585  22157-22227/cn.wecook.app D/dalvikvm﹕ threadid=12: notify debugger
09-22 18:38:39.585  22157-22227/cn.wecook.app D/dalvikvm﹕ threadid=12 (SharedPreferencesImpl-load): calling run()
09-22 18:38:39.598  22157-22227/cn.wecook.app D/dalvikvm﹕ threadid=12: exiting
09-22 18:38:39.598  22157-22227/cn.wecook.app D/dalvikvm﹕ threadid=12: bye!
09-22 18:38:39.635  22157-22157/cn.wecook.app D/NativeCrypto﹕ NativeCrypto_EVP_VerifyInit ctx=0x79224a80
09-22 18:38:39.635  22157-22157/cn.wecook.app D/NativeCrypto﹕ NativeCrypto_EVP_VerifyInit algorithmChars=RSA-SHA1
09-22 18:38:39.647  22157-22157/cn.wecook.app D/NativeCrypto﹕ NativeCrypto_EVP_VerifyInit ctx=0x79225fb8
09-22 18:38:39.647  22157-22157/cn.wecook.app D/NativeCrypto﹕ NativeCrypto_EVP_VerifyInit algorithmChars=RSA-SHA1
09-22 18:38:39.663  22157-22157/cn.wecook.app D/NativeCrypto﹕ NativeCrypto_EVP_VerifyInit ctx=0x7934d700
09-22 18:38:39.663  22157-22157/cn.wecook.app D/NativeCrypto﹕ NativeCrypto_EVP_VerifyInit algorithmChars=RSA-SHA1
09-22 18:38:39.673  22157-22157/cn.wecook.app D/dalvikvm﹕ open_cached_dex_file : /data/data/cn.wecook.app/files/apatch/filetest.apatch /data/data/cn.wecook.app/files/apatch_opt/filetest.apatch
09-22 18:38:39.690  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.COS_45 flag:
09-22 18:38:39.690  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.690  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.SHADOW_BOTTOM_SCALE flag:
09-22 18:38:39.690  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.690  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.SHADOW_HORIZ_SCALE flag:
09-22 18:38:39.690  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.SHADOW_MULTIPLIER flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.SHADOW_TOP_SCALE flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mEdgeShadowPaint flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mContentBounds flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mCornerShadowPath flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mCornerShadowPaint flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mCornerRadius flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mDirty flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mAddPaddingForCorners flag:
09-22 18:38:39.691  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mMaxShadowSize flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mPrintedShadowClipWarning flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mRawMaxShadowSize flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mRawShadowSize flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mShadowEndColor flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mShadowMiddleColor flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mShadowSize flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper.mShadowStartColor flag:
09-22 18:38:39.692  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.693  22157-22157/cn.wecook.app W/dalvikvm﹕ DexOpt: resolve class illegal access: Landroid/support/design/widget/ShadowDrawableWrapper_CF; -> Landroid/support/design/widget/ShadowDrawableWrapper;
09-22 18:38:39.693  22157-22157/cn.wecook.app I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x0013 at 0x05 in Landroid/support/design/widget/ShadowDrawableWrapper_CF;.calculateHorizontalPadding
09-22 18:38:39.693  22157-22157/cn.wecook.app W/dalvikvm﹕ DexOpt: resolve class illegal access: Landroid/support/design/widget/ShadowDrawableWrapper_CF; -> Landroid/support/design/widget/ShadowDrawableWrapper;
09-22 18:38:39.693  22157-22157/cn.wecook.app I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x0013 at 0x08 in Landroid/support/design/widget/ShadowDrawableWrapper_CF;.calculateVerticalPadding
09-22 18:38:39.693  22157-22157/cn.wecook.app D/AndFix﹕ dalvikMethod: buildShadowCorners
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.COS_45 flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.SHADOW_BOTTOM_SCALE flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.SHADOW_HORIZ_SCALE flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.SHADOW_MULTIPLIER flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.SHADOW_TOP_SCALE flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 25
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mEdgeShadowPaint flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mContentBounds flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mCornerShadowPath flag:
09-22 18:38:39.694  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mCornerShadowPaint flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mCornerRadius flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mDirty flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mAddPaddingForCorners flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mMaxShadowSize flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mPrintedShadowClipWarning flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mRawMaxShadowSize flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mRawShadowSize flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mShadowEndColor flag:
09-22 18:38:39.695  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mShadowMiddleColor flag:
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mShadowSize flag:
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 1
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndFix﹕ modify android.support.design.widget.ShadowDrawableWrapper_CF.mShadowStartColor flag:
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndFix﹕ dalvik_setFieldFlag: 17
09-22 18:38:39.696  22157-22157/cn.wecook.app W/dalvikvm﹕ Interface 'Landroid/support/v4/animation/AnimatorProvider;' is not accessible to 'Landroid/support/v4/animation/HoneycombMr1AnimatorCompatProvider_CF;'
09-22 18:38:39.696  22157-22157/cn.wecook.app W/dalvikvm﹕ Link of class 'Landroid/support/v4/animation/HoneycombMr1AnimatorCompatProvider_CF;' failed
09-22 18:38:39.696  22157-22157/cn.wecook.app D/AndroidRuntime﹕ Shutting down VM
09-22 18:38:39.696  22157-22157/cn.wecook.app W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41ce8d10)
09-22 18:38:39.696  22157-22157/cn.wecook.app W/dalvikvm﹕ threadid=1: uncaught exception occurred
09-22 18:38:39.696  22157-22157/cn.wecook.app W/System.err﹕ java.lang.IllegalAccessError: interface not accessible
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at dalvik.system.DexFile.defineClassNative(Native Method)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at dalvik.system.DexFile.defineClass(DexFile.java:222)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at dalvik.system.DexFile.loadClass(DexFile.java:204)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:169)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:203)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at com.wecook.common.modules.hotfix.HotFixTools.setup(HotFixTools.java:40)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at com.wecook.common.modules.ModuleManager.registerAllModules(ModuleManager.java:104)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at com.wecook.common.app.BaseApp.onCreate(BaseApp.java:40)
09-22 18:38:39.729  22157-22157/cn.wecook.app W/System.err﹕ at cn.wecook.app.WecookApp.onCreate(WecookApp.java:38)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4574)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.app.ActivityThread.access$1500(ActivityThread.java:155)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:110)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.os.Looper.loop(Looper.java:193)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5332)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
09-22 18:38:39.730  22157-22157/cn.wecook.app W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
09-22 18:38:39.731  22157-22157/cn.wecook.app W/dalvikvm﹕ threadid=1: calling UncaughtExceptionHandler
09-22 18:38:39.731  22157-22157/cn.wecook.app I/dalvikvm﹕ +++ calling Ljava/lang/ThreadGroup;.uncaughtException
09-22 18:38:39.738  22157-22157/cn.wecook.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cn.wecook.app, PID: 22157
    java.lang.IllegalAccessError: interface not accessible
            at dalvik.system.DexFile.defineClassNative(Native Method)
            at dalvik.system.DexFile.defineClass(DexFile.java:222)
            at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
            at dalvik.system.DexFile.loadClass(DexFile.java:204)
            at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:169)
            at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:203)
            at com.wecook.common.modules.hotfix.HotFixTools.setup(HotFixTools.java:40)
            at com.wecook.common.modules.ModuleManager.registerAllModules(ModuleManager.java:104)
            at com.wecook.common.app.BaseApp.onCreate(BaseApp.java:40)
            at cn.wecook.app.WecookApp.onCreate(WecookApp.java:38)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4574)
            at android.app.ActivityThread.access$1500(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5332)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by supern** [comment]
你是用apkpatch-1.0.3吗

**Comment by kevinet** [comment]
@supern 替换成1.0.3的已经成功

**Comment by supern** [comment]
@kevinet 好的
