### ISSUE TITLE
混淆后打差分包，诡异的事情发生了

### ISSUE THREAD

**Issue by anzyhui** [alibaba/AndFix#250]
验证了很多次了，都出现这情况，
proguard就不列了，都是一样的，
得到差分包后，把diff.dex逆向，得到的class信息如下：
`package com.example.multidexapplication;

import com.alipay.euler.andfix.annotation.MethodReplace;

public class a_CF
{
  @MethodReplace(clazz="com.example.multidexapplication.a", method="a")
  public String a()
  {
    return "出现BUG,已经修复";
  }
}`
这好像没什么异常，但是，左侧类描述是：
![image](https://cloud.githubusercontent.com/assets/15945043/18502979/10f84ae4-7a8d-11e6-8419-3da3366dd6ba.png)

这是咋回事？？为啥文件名描述与类名不一致呢？
@mazhao @perusio

**Comment by supern** [comment]
@anzyhui  是这样的，会加上_CF

**Comment by anzyhui** [comment]
@不是呀，我说的是，类名被混淆成了a，但是差分包里面按说应该是a_CF，但是为啥是b_CF。
不过我重新混淆打包，这个问题又不存在了，应该是我当时混淆出了问题，还是感谢。
