### ISSUE TITLE
如果已经打过补丁，再次打补丁的话，如何生成补丁呀？

### ISSUE THREAD

**Issue by just-for-you** [alibaba/AndFix#251]
如果发布的应用已经打过补丁，需要再次打补丁的话，新的补丁包如何生成呀，是用最新的APK和最原始的补丁生成补丁包，还是用最新的APK和打过补丁的APK生成补丁？

**Comment by just-for-you** [comment]
求大神指点。。。

**Comment by ContinueCoding** [comment]
今天刚遇到同样的问题，我的解决方法是：每次都和最原始的apk生成最新的*.apatch文件，然后在前端下载此补丁文件，但是在addPatch(path)之前先调用PatchManager.removeAllPatch()方法移除之前所有的补丁文件，再通过SharedPreferences sp = getSharedPreferences("_andfix_", Context.MODE_PRIVATE);
sp.edit().putString("version", getVersionName()).commit();保存最新的versionName！

**Comment by just-for-you** [comment]
谢谢大神提供方案^_^
