### ISSUE TITLE
基类的方法被修改后，其子类 override 该函数失效

### ISSUE THREAD

**Issue by fashare2015** [alibaba/AndFix#255]
>我仅仅修改了基类 BaseWebActivity.onResume() 方法，打了个补丁包。
出现的问题是它的子类 MyWebActivity.onResume() 未被正确调用。

这是报出的 log: ( incorrectly overridden ??? )
>W/art: **Before Android 4.1**, method void com.xxx.xxx.MyWebActivity.**onResume()** would have **incorrectly overridden** the **package-private method** in com.xxx.xxx.BaseWebActivity_CF

4.4是正常的，在若干 5.0，5.1，6.0 机器上出现该问题（包括Moto X Pro, Nexus 5，华为，sony等）

**Comment by xxxzhi** [comment]
@supern 可以请教一下么？ 为什么替换成  dmeth->access_flags_ & (~0x0002) | 0x0001; 就好了呢？

**Comment by fashare2015** [comment]
@xxxzhi 俺也不懂JNI，感觉完全在看魔法

**Comment by supern** [comment]
@xxxzhi  @fashare2015  andfix是把fix后的方法放在新的类，而"子类"访问基类的方法没有权限，把他改成public的就可以了

**Comment by fashare2015** [comment]
@supern 了解了，thx

**Comment by xxxzhi** [comment]
@supern 嗯，谢谢。另外我查了下函数标识的头文件[modifiers.h](https://android.googlesource.com/platform/art/+/master/runtime/modifiers.h#22)，有这个会更清楚:

```

static constexpr uint32_t kAccPublic =       0x0001;  // class, field, method, ic
static constexpr uint32_t kAccPrivate =      0x0002;  // field, method, ic
static constexpr uint32_t kAccProtected =    0x0004;  // field, method, ic
static constexpr uint32_t kAccStatic =       0x0008;  // field, method, ic
static constexpr uint32_t kAccFinal =        0x0010;  // class, field, method, ic
static constexpr uint32_t kAccSynchronized = 0x0020;  // method (only allowed on natives)
static constexpr uint32_t kAccSuper =        0x0020;  // class (not used in dex)
static constexpr uint32_t kAccVolatile =     0x0040;  // field
static constexpr uint32_t kAccBridge =       0x0040;  // method (1.5)
static constexpr uint32_t kAccTransient =    0x0080;  // field
static constexpr uint32_t kAccVarargs =      0x0080;  // method (1.5)
static constexpr uint32_t kAccNative =       0x0100;  // method
static constexpr uint32_t kAccInterface =    0x0200;  // class, ic

```

[modifiers.h](https://android.googlesource.com/platform/art/+/master/runtime/modifiers.h#22)
