### ISSUE TITLE
gradle 2.2.0生成的apk无法用apkpatch生成apatch文件

### ISSUE THREAD

**Issue by lawrencewqy** [alibaba/AndFix#257]
升级最新的android studio 2.2以后，build tools升级到com.android.tools.build:gradle:2.2.0，生成的apk文件无法用apkpatch工具生成apatch文件

**Comment by landryshuai** [comment]
估计是你开启了instantrun

**Comment by supern** [comment]
嗯，instantrun

**Comment by lawrencewqy** [comment]
一直是用gradlew命令在terminal里面打包，不牵扯instantrun吧，同一个工程，把com.android.tools.build:gradle:2.2.0改成com.android.tools.build:gradle:2.1.3就能成功生成apatch文件。
