### ISSUE TITLE
一直出现IncompatibleClassChangeError，不只为何，麻烦看下

### ISSUE THREAD

**Issue by mabeijianxi** [alibaba/AndFix#265]
java.lang.IncompatibleClassChangeError: The method 'void com.henanjianye.soon.communityo2o.fragment.bg_CF.a()' was expected to be of type direct but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
                                                                                       at com.henanjianye.soon.communityo2o.fragment.bg.initView(Fragment03.java:118)
                                                                                       at com.henanjianye.soon.communityo2o.fragment.a.onViewCreated(BaseFragment.java:107)
                                                                                       at android.support.v4.app.x.a(FragmentManager.java:1045)

**Comment by sanemars** [comment]
I have encountered this problem.
here is my stacktrace
D/AndFix: vm is: art , apilevel is: 23
D/OpenSSLLib: OpensslErr:Module:12(116:176); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:186;Function:ASN1_get_object
D/MainActivity: inited.
D/MainActivity: apatch loaded.
D/OpenSSLLib: OpensslErr:Module:12(116:176); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:186;Function:ASN1_get_object
D/OpenSSLLib: OpensslErr:Module:12(116:176); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:186;Function:ASN1_get_object

FATAL EXCEPTION: main
                                                                                Process: andfix.sace.com.andfixpractise, PID: 17019
                                                                                java.lang.IncompatibleClassChangeError: The method 'void andfix.sace.com.andfixpractise.SecondActivity_CF.initData()' was expected to be of type direct but instead was found to be of type virtual (declaration of 'andfix.sace.com.andfixpractise.SecondActivity' appears in /data/app/andfix.sace.com.andfixpractise-2/base.apk)

**Comment by supern** [comment]
反射调用吗？

**Comment by solomon2** [comment]
`10-25 16:03:46.159 7582-7582/? E/TEST: TEST.
10-25 16:03:46.164 7582-7582/? D/AndFix: vm is: art , apilevel is: 23
10-25 16:03:46.188 7582-7582/? E/TEST: inited.
10-25 16:03:46.211 7582-7582/? D/AndFix: modify com.jhqc.andfixtest.MainActivity.tv flag:
10-25 16:03:46.211 7582-7582/? D/AndFix: setFieldFlag_6_0: 1 
10-25 16:03:46.212 7582-7582/? D/AndFix: replace_6_0: -1268486027 , -1268486027
10-25 16:03:46.212 7582-7582/? D/AndFix: modify com.jhqc.andfixtest.MainActivity_CF.tv flag:
10-25 16:03:46.212 7582-7582/? D/AndFix: setFieldFlag_6_0: 1 
10-25 16:03:46.212 7582-7582/? E/TEST: apatch loaded.
10-25 16:03:46.214 7582-7582/? D/PatchManager: patch [/storage/emulated/0/out.apatch] has be loaded.
10-25 16:03:46.214 7582-7582/? E/TEST: apatch:/storage/emulated/0/out.apatch added.
10-25 16:03:46.249 7582-7582/? E/TEST: testAndFix TEST 
10-25 16:03:46.249 7582-7582/? D/AndroidRuntime: Shutting down VM
                                                 
                                                 
                                                 --------- beginning of crash
10-25 16:03:46.249 7582-7582/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.jhqc.andfixtest, PID: 7582
                                                 java.lang.IncompatibleClassChangeError: The method 'java.lang.String com.jhqc.andfixtest.MainActivity_CF.testAndFix()' was expected to be of type direct but instead was found to be of type virtual (declaration of 'com.jhqc.andfixtest.MainActivity' appears in /data/app/com.jhqc.andfixtest-1/base.apk)
                                                     at com.jhqc.andfixtest.MainActivity.onCreate(MainActivity.java:24)
                                                     at android.app.Activity.performCreate(Activity.java:6303)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
10-25 16:03:46.251 1533-3032/? W/ActivityManager:   Force finishing activity com.jhqc.andfixtest/.MainActivity
10-25 16:03:46.252 3454-3705/? I/WtEventController: Receive am_crash event for pid: 7582`




我也存在这个问题，模拟器测试通过， 小米3出问题，
刚更新了最新版本    compile 'com.alipay.euler:andfix:+'

Android版本 6.0.1
MIUI8  6.9.29

**Comment by sanemars** [comment]
@supern 没有使用反射调用

**Comment by solomon2** [comment]
```
10-25 17:16:31.348 21412-21412/? D/TEST: inited.
10-25 17:16:31.349 21412-21412/? D/TEST: apatch loaded.
10-25 17:16:31.411 21430-21430/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.jhqc.myapplication/files/apatch/out.apatch --oat-file=/data/user/0/com.jhqc.myapplication/files/apatch_opt/out.apatch
10-25 17:16:31.445 21430-21430/? I/dex2oat: dex2oat took 34.800ms (threads: 4) arena alloc=12KB java alloc=20KB native alloc=994KB free=1053KB
10-25 17:16:31.460 21412-21412/? D/AndFix: replace_6_0: -1277636347 , -1277636347
10-25 17:16:31.461 21412-21412/? D/TEST: apatch:/storage/emulated/0/out.apatch added.
10-25 17:16:31.481 21412-21412/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-25 17:16:31.509 21412-21412/? V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
10-25 17:16:31.509 21412-21412/? V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
10-25 17:16:31.509 21412-21412/? V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
10-25 17:16:31.509 21412-21412/? V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
10-25 17:16:31.509 21412-21412/? V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
10-25 17:16:31.512 21412-21412/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@fdb44f8
10-25 17:16:31.512 21412-21412/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f301dd1
10-25 17:16:31.545 21412-21412/? A/art: art/runtime/entrypoints/quick/quick_trampoline_entrypoints.cc:923] Check failed: called != nullptr void com.jhqc.myapplication.TEST_CF.test() com.jhqc.myapplication.TEST virtual 12
10-25 17:16:31.676 21412-21412/? A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
10-25 17:16:31.676 21412-21412/? A/art: art/runtime/runtime.cc:366] Runtime aborting --- recursively, so no thread-specific detail!
10-25 17:16:31.676 21412-21412/? A/art: art/runtime/runtime.cc:366] 
                                        
                                        --------- beginning of crash
10-25 17:16:31.676 21412-21412/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 21412 (c.myapplication)
10-25 17:16:31.794 286-286/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-25 17:16:31.794 286-286/? A/DEBUG: Build fingerprint: 'Xiaomi/cancro/cancro:6.0.1/MMB29M/6.9.29:user/release-keys'
10-25 17:16:31.794 286-286/? A/DEBUG: Revision: '0'
10-25 17:16:31.794 286-286/? A/DEBUG: ABI: 'arm'
10-25 17:16:31.794 286-286/? A/DEBUG: pid: 21412, tid: 21412, name: c.myapplication  >>> com.jhqc.myapplication <<<
10-25 17:16:31.794 286-286/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-25 17:16:31.786 286-286/? W/debuggerd: type=1400 audit(0.0:324903): avc: denied { search } for name="com.jhqc.myapplication" dev="mmcblk0p25" ino=737374 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
10-25 17:16:31.814 286-286/? A/DEBUG: Abort message: 'art/runtime/entrypoints/quick/quick_trampoline_entrypoints.cc:923] Check failed: called != nullptr void com.jhqc.myapplication.TEST_CF.test() com.jhqc.myapplication.TEST virtual 12'
10-25 17:16:31.814 286-286/? A/DEBUG:     r0 00000000  r1 000053a4  r2 00000006  r3 b6f7bb7c
10-25 17:16:31.814 286-286/? A/DEBUG:     r4 b6f7bb84  r5 b6f7bb34  r6 00000001  r7 0000010c
10-25 17:16:31.814 286-286/? A/DEBUG:     r8 b4abf800  r9 b4abde44  sl ad6f6adb  fp b4aa3488
10-25 17:16:31.814 286-286/? A/DEBUG:     ip 00000006  sp beb0ea48  lr b6ce0c51  pc b6ce3040  cpsr 40070010
10-25 17:16:31.829 286-286/? A/DEBUG: backtrace:
10-25 17:16:31.829 286-286/? A/DEBUG:     #00 pc 00042040  /system/lib/libc.so (tgkill+12)
10-25 17:16:31.830 286-286/? A/DEBUG:     #01 pc 0003fc4d  /system/lib/libc.so (pthread_kill+32)
10-25 17:16:31.830 286-286/? A/DEBUG:     #02 pc 0001c3fb  /system/lib/libc.so (raise+10)
10-25 17:16:31.830 286-286/? A/DEBUG:     #03 pc 000195ad  /system/lib/libc.so (__libc_android_abort+34)
10-25 17:16:31.830 286-286/? A/DEBUG:     #04 pc 00017500  /system/lib/libc.so (abort+4)
10-25 17:16:31.830 286-286/? A/DEBUG:     #05 pc 00333909  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
10-25 17:16:31.831 286-286/? A/DEBUG:     #06 pc 000f460b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
10-25 17:16:31.831 286-286/? A/DEBUG:     #07 pc 000f08e1  /system/lib/libart.so (_ZN3art7BarrierD2Ev+216)
10-25 17:16:31.831 286-286/? A/DEBUG:     #08 pc 0035b40b  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+162)
10-25 17:16:31.831 286-286/? A/DEBUG:     #09 pc 003339cd  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+424)
10-25 17:16:31.831 286-286/? A/DEBUG:     #10 pc 000f460b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
10-25 17:16:31.832 286-286/? A/DEBUG:     #11 pc 003ff431  /system/lib/libart.so (artQuickResolutionTrampoline+1144)
10-25 17:16:31.832 286-286/? A/DEBUG:     #12 pc 000ea9b3  /system/lib/libart.so (art_quick_resolution_trampoline+34)
10-25 17:16:31.832 286-286/? A/DEBUG:     #13 pc 004fe441  /data/app/com.jhqc.myapplication-1/oat/arm/base.odex (offset 0x330000)
10-25 17:16:32.033 1533-1667/? I/Timeline: Timeline: App_transition_stopped time:564595922
10-25 17:16:32.210 3454-3705/? I/WtEventController: Receive am_crash event for pid: 1533
10-25 17:16:32.210 286-286/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
10-25 17:16:32.212 286-286/? E/DEBUG: AM write failed: Broken pipe
10-25 17:16:32.213 1533-21444/? W/ActivityManager:   Force finishing activity com.jhqc.myapplication/.MainActivity
```

@supern 请看下， 我测试了很多次， 在小米3上只能修复 public static方法， 其他都不行

**Comment by supern** [comment]
@solomon2  可以看下你这个类的代码不

**Comment by solomon2** [comment]
@supern 仿照demo写的简单测试。

```
public class MainActivity extends AppCompatActivity {
    // Used to load the 'native-lib' library on application startup.
    static {
        System.loadLibrary("native-lib");
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        new TEST().test();

    }

}

public class TEST {

    public  void test(){
        Log.e("TEST", "XOXOXOXOX");
        HOHOHOH();
    }
    public  void HOHOHOH(){
        Log.e("TEST", "666666666666666");
        Log.e("TEST", "9999999999999999");
    }

}

public class app extends Application {
    private static final String TAG = "TEST";
    private static final String APATCH_PATH = "/out.apatch";
    /**
     * patch manager
     */
    private PatchManager mPatchManager;
    @Override
    public void onCreate() {
        super.onCreate();
        // initialize
        mPatchManager = new PatchManager(this);
        mPatchManager.init("1.0");
        Log.d(TAG, "inited.");

        // load patch
        mPatchManager.loadPatch();
        Log.d(TAG, "apatch loaded.");

        // add patch at runtime
        try {
            // .apatch file path
            String patchFileString = Environment.getExternalStorageDirectory()
                    .getAbsolutePath() + APATCH_PATH;
            mPatchManager.addPatch(patchFileString);
            Log.d(TAG, "apatch:" + patchFileString + " added.");
        } catch (Exception e) {
            Log.e(TAG, "", e);
        }
    }
}
```

**Comment by supern** [comment]
@solomon2  没有testAndFix这个方法啊

**Comment by supern** [comment]
@sanemars @mabeijianxi 能贴一下代码不

**Comment by solomon2** [comment]
@supern 抱歉，刚才贴的是第二次反馈的日志， 第一次报错的日志代码如下：

```
public class MainActivity extends Activity  {

    TextView tv;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Log.e("TEST", "testAndFix TEST ");

        tv = (TextView) findViewById(R.id.sample_text);
        tv.setText(testAndFix());
    }

    private String testAndFix(){
        Log.e("TEST", "testAndFix 2222222222 ");
        return "AndFix 2222222222";
    }


}
```

**Comment by solomon2** [comment]
Fix前后的变化：只改了testAndFix方法内打印的Log和返回的String

**Comment by sanemars** [comment]
有bug的代码
`public class SecondActivity extends AppCompatActivity {

    private final static String TAG = SecondActivity.class.getSimpleName();

    TextView tvBug;

    private long start_millis;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_seconde);
        this.start_millis = System.currentTimeMillis();
        this.initData();
        this.showToast("程序正常运行");

    }


    //initialize data
    private void initData() {
        // make a exception
        this.tvBug.setText("");

    }


    private void showToast(String msg) {
        Toast.makeText(this, msg, Toast.LENGTH_SHORT).show();
    }

    @Override
    protected void onStart() {
        super.onStart();
        this.showToast("启动耗时:" + (System.currentTimeMillis() - this.start_millis) + "毫秒");
    }
}`

修复bug的代码
`public class SecondActivity extends AppCompatActivity {

    private final static String TAG = SecondActivity.class.getSimpleName();

    TextView tvBug;

    private long start_millis;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_seconde);
        this.start_millis = System.currentTimeMillis();
        this.initData();
        this.showToast("程序正常运行");

    }


    //initialize data
    private void initData() {
        // make a exception
        //this.tvBug.setText("");

    }


    private void showToast(String msg) {
        Toast.makeText(this, msg, Toast.LENGTH_SHORT).show();
    }

    @Override
    protected void onStart() {
        super.onStart();
        this.showToast("启动耗时:" + (System.currentTimeMillis() - this.start_millis) + "毫秒");
    }
}`

**Comment by supern** [comment]
@sanemars @solomon2  试试新版本

**Comment by sanemars** [comment]
@supern 使用新版班后，还是报一样的错误。
你那边在 67a5e3c 更新了so库，
可是我使用 新版 打到apk中的还是 旧版的so库.

**Comment by supern** [comment]
@sanemars 需要换新的so

**Comment by sanemars** [comment]
@supern 这样 设置依赖  compile 'com.alipay.euler:andfix:0.5.0@aar'
拿不到新的so?

**Comment by sanemars** [comment]
@supern 使用新版本 没有这个问题了

**Comment by ContinueCoding** [comment]
@sanemars 请教一下，我们在用AndFix时也遇到了同样的问题IncompatibleClassChangeError，我们是在8月份接入的andfix（V0.4.0），到了9月18日看到升级到了V0.5.0，就只把compile引用中的版本号改了一下。看你们上面讨论说需要更换新的so文件？具体怎么操作的？谢谢答复！P.S.我们的线上包是用的Jenkins自动打包，我本地和Jenkins远程仓库的so文件都是最新的（/app/build/intermediates/exploded-aar/com.alipay.euler/andfix/0.5.0/jni/*）！

**Comment by sanemars** [comment]
@ContinueCoding 
1.我这边配置 远程依赖也是获取不到最新的so文件。
2.我直接clone整个工程 作为本地依赖 。
![1](https://cloud.githubusercontent.com/assets/10831818/19954087/d7a5ee28-a1af-11e6-8114-6111e7edb1a1.PNG)
![2](https://cloud.githubusercontent.com/assets/10831818/19954089/dc6f4a1c-a1af-11e6-9dbd-40b24d06e946.PNG)

**Comment by ContinueCoding** [comment]
@sanemars 下载整个工程后（解压得到AndFix-master），怎么作为本地依赖的？试了一下（import module\library），一直操作不成功。

**Comment by sanemars** [comment]
@ContinueCoding 不要直接导入。建议 自己建一个包名一样的工程，手动导入.

**Comment by ContinueCoding** [comment]
@sanemars 谢谢答复！ @supern 你在上面说的更换新的so文件，可以这样理解吗：在首次接入AndFix打包时，会在/app/build/intermediates/exploded-aar/com.alipay.euler/andfix/0.5.0目录生成相应的so文件，但是之后再打包时不会生成新的so文件，而这些老so文件会产生IncompatibleClassChangeError错误。你6天前最近的一次提交解决了这个bug，我们如果想要替换新so文件，就需要先删除之前生成的老so文件，再次打包（生成新so文件）就可以吗？

**Comment by sanemars** [comment]
@supern @ContinueCoding  清理工程，重新配置依赖，我都试过。依然无法获取最新的so。
最后没办法 做了本地依赖.

**Comment by ContinueCoding** [comment]
@sanemars 你先把/app/build/intermediates/exploded-aar/com.alipay.euler 删除，然后再编译就可以生成新的so文件，但不知道是不是 @supern 说的新so文件。我猜测是这样的，但只能在下个版本验证了。

**Comment by ContinueCoding** [comment]
@sanemars  @supern 更新一下问题，本地so文件的目录是在C:\Users\xxx\.gradle\caches\modules-2\files-2.1\com.alipay.euler\andfix\0.5.0？

**Comment by supern** [comment]
@ContinueCoding 是的，不把C:\Users\xxx.gradle\caches\modules-2\files-2.1\com.alipay.euler\删除再更新下试试
