### ISSUE TITLE
正式项目addPatch时崩溃，重新启动后发现补丁已经生效，并没有抓到应用层的崩溃日志，请问可能是什么问题？

### ISSUE THREAD

**Issue by maplebilly** [alibaba/AndFix#266]
问题如上

已经在混淆中加入了applymapping，
已经使用了支持multiDex的apatch.jar
已经在单独的轻量级项目中测试通过

仅仅是修改一个Toast，目前没抓到错误日志，正在尝试确定错误原因和位置，
麻烦知道哪里出错或者可能出错的地方 提点一下 好节省时间 

thank

**Comment by JackyAnn** [comment]
不要再当前在运行的类中加载补丁，容易出错。建议将补丁的加载放到广播或者intentservice中，它们的生命周期比较短，补丁可以立即生效。

**Comment by maplebilly** [comment]
@JackyAnn 果然是这个问题，多谢啦，我再继续测试了
