### ISSUE TITLE
需要清除app的数据，才能修复成功

### ISSUE THREAD

**Issue by cock-tail** [alibaba/AndFix#27]
1.在没有out.apatch的情况下，打开adnfixdemo
2.关闭demo
3.将out.apatch放到SD卡中
4.打开demo，还是运行原来的，没有修复成功
5.到应用信息中，清除数据
6.再打开demo，修复成功了

不知道这是为什么，如果每次都需要清除数据，感觉不怎么实用？？？

**Comment by supern** [comment]
@cock-tail  这个已经fix了，更新代码试试

**Comment by cock-tail** [comment]
我用的是 compile 'com.alipay.euler:andfix:0.3.1@aar' 这个不是最新的吗？@supern

**Comment by supern** [comment]
@cock-tail 不是哦，建议你用源码试试。

**Comment by cock-tail** [comment]
嗯嗯  发现了，你们代码更新之后  gradle那边没有更新

**Comment by supern** [comment]
@cock-tail 重新部署了下
