### ISSUE TITLE
编译Andfix源码时，art_method_replace_7_0.cpp总是抱错

### ISSUE THREAD

**Issue by zhouaijia** [alibaba/AndFix#273]
我在编译Andfix时，总是会报如下错误：
Error:(57, 74) error: assigning to 'art::mirror::Class::Status' from incompatible type 'int'
E:\AS-Project\Jni\app\src\main\cpp\art\art_method_replace_7_0.cpp
Warning:(80, 4) warning: format specifies type 'int' but the argument has type 'void *' [-Wformat]
Warning:(81, 4) warning: format specifies type 'int' but the argument has type 'void *' [-Wformat]
Warning:(88, 52) warning: '&' within '|' [-Wbitwise-op-parentheses]
Information:(88, 52) note: place parentheses around the '&' expression to silence this warning

就是在这段代码出了错：reinterpret_cast<art::mirror::Class*>(dmeth->declaring_class_)->status_ =
			reinterpret_cast<art::mirror::Class*>(smeth->declaring_class_)->status_ -1;
是类型不兼容错误。
 
请问大神，我该如何处理这个错误呢？

**Comment by nickchenjian** [comment]
这个你直接使用ndk-build  编译  清一下环境  应该是没有问题的

**Comment by zhouaijia** [comment]
多谢大神指点。
      经过研究后发现，对于int转enum，c与c++支持不一样，c可以隐式地将int转换成enum，而c++不可以，所以如果用gcc进行编译的话是没有问题的，但若使用g++进行编译，就会报类型转换的错误。

**Comment by ustcxiaoyu** [comment]
hi 你现在编译成功了么  怎么编译的呢

**Comment by zhouaijia** [comment]
新建一个jni工程，然后把andfix的java代码和jni代码复制到工程里面，最后直接进行编译即可

编译jni代码时如果出现类型转换错误，就将其强转一下即可，具体如下：
把art_method_replace_7_0.cpp文件的第58行代码修改为
reinterpret_cast<art::mirror::Class*>(dmeth->declaring_class_)->status_ =
(art::mirror::Class::Status)(reinterpret_cast<art::mirror::Class*>(smeth->declaring_class_)->status_ -1);

把dalvik_method_replace.cpp文件的第57行到65行修改为
dvmDecodeIndirectRef_fnPtr = (dvmDecodeIndirectRef_func)dvm_dlsym(dvm_hand,
				apilevel > 10 ?
						"_Z20dvmDecodeIndirectRefP6ThreadP8_jobject" :
						"dvmDecodeIndirectRef");
		if (!dvmDecodeIndirectRef_fnPtr) {
			return JNI_FALSE;
		}
		dvmThreadSelf_fnPtr = (dvmThreadSelf_func)dvm_dlsym(dvm_hand,
				apilevel > 10 ? "_Z13dvmThreadSelfv" : "dvmThreadSelf");
