### ISSUE TITLE
补丁修复失败时怎么回退？

### ISSUE THREAD

**Issue by LinPom** [alibaba/AndFix#304]
部分手机AndFix加载补丁失败时会导致应用无法正常运行，比修复bug前更严重，这种场景能回退到修复bug前的状态吗

**Comment by supern** [comment]
删除补丁

**Comment by LinPom** [comment]
谢谢，我现在的处理就是删除补丁，确实可以回退到修复前的状态，但是新的问题来了，怎么监听AndFix修复失败导致应用无法运行的情况呢？如果补丁发布出去之后，不知道修复成功了还是失败了，总不能看crash统计来猜呀，貌似百川的HotFix有内部引擎加载异常这种监听回调，AndFix能提供这种方法吗

**Comment by supern** [comment]
@LinPom  捕获异常，分析是AndFix引起的就可以执行删除，目前没有提供

**Comment by LinPom** [comment]
OK，多谢
