### ISSUE TITLE
使用apkpatch－1.0.3,成功制作apatch，但是无输出，补丁无效。

### ISSUE THREAD

**Issue by 11447416** [alibaba/AndFix#336]
全程没有报错，out文件如下：
4-86112f4778c67a620082b737ae673830.apatch
diff.dex
smali
其中smali里面没有内容，执行patch的时候，也没有任何输出，正常的时候，会输出modify呀，这个是apkpatch的bug嚒？修改的内容是activity的initUI函数，声明是这样的
 void initUI() {}
。

使用这个apatch也没有任何效果l。

无论如何，感谢作者的付出和开源。

**Comment by SaraLee12** [comment]
我也遇到了一模一样的问题，但是集成在我的另一个工程里就是好的。
有没有可能是因为我集成了阿里的客服模块，依赖的包如下
 'com.alibaba.mobileim:IMCore:2.0.2.1@aar' 和 'com.alibaba.mobileim:IMKit:2.0.2.1@aar'
我搜了半天也没搜到遇到这个问题的

**Comment by panq-jack** [comment]
同样，无报错，不会有modify。。

**Comment by Allansk2** [comment]
请问已经有人解决这个问题了吗

**Comment by 11447416** [comment]
我估计是工具的bug，目前我已经放弃这个玩意儿了，毕竟已经他支持的有限，建议尝试阿里的商业化解决方案或者其他方案。
