### ISSUE TITLE
关于sample的疑惑

### ISSUE THREAD

**Issue by Rowandjj** [alibaba/AndFix#48]
我这边跑demo的时候打出来如下日志（增加patch包后）：
10-09 06:21:39.693 457-457/? D/euler: inited.
10-09 06:21:39.697 457-457/? D/euler: apatch loaded.
10-09 06:21:39.697 457-457/? D/euler: apatch:/storage/emulated/0/out.apatch added.
10-09 06:21:39.699 457-457/? I/euler: fix succes
10-09 06:21:39.699 457-457/? E/euler: b
10-09 06:21:39.699 457-457/? E/euler: s1
10-09 06:21:39.699 457-457/? E/euler: 10==a
10-09 06:21:39.699 457-457/? I/euler: fix success
10-09 06:21:39.699 457-457/? I/euler: a
10-09 06:21:39.699 457-457/? E/euler: 0
10-09 06:21:39.699 457-457/? E/euler: i=10

=========
i变量并没有更改为11，这是怎么回事？静态变量更改无效么？

**Comment by supern** [comment]
@Rowandjj 静态变量没有更改啊，更改需要在方法里面
