### ISSUE TITLE
脚本命令有问题

### ISSUE THREAD

**Issue by AndroidFa** [alibaba/AndFix#97]
我执行的命令：
 apkpath -f </ceshi/new/a2.apk> -t </ceshi/old/a1.apk> -o </ceshi/out> -k </ceshi/qian/aa.jks> -p <123123> -a </ceshi/out/out.apatch> -e <123456>
但是却提示我：
syntax error near unexpected token `123123'

**Comment by THEONE10211024** [comment]
把"<>"符号去掉

**Comment by AndroidFa** [comment]
好的
